#!/bin/sh

FILEPATH="$1"

# Metadata
CREATED_DATE=$(exif "$1" --tag="Date and Time (Original)" -m | cut -d' ' -f1 | sed 's/:/\//g')
X_DIMENSION=$(exif "$1" --tag="Pixel X Dimension" -m)
Y_DIMENSION=$(exif "$1" --tag="Pixel Y Dimension" -m)
FOCAL_LENGTH=$(exif "$1" --tag="Focal Length" -m)
F_NUMBER=$(exif "$1" --tag="F-Number" -m)
EXP_TIME=$(exif "$1" --tag="Exposure Time" -m | cut -d' ' -f1)
ISO=$(exif "$1" --tag="ISO Speed Ratings" -m)



echo "$FILEPATH :: $CREATED_DATE · ${X_DIMENSION}x${Y_DIMENSION}px ($((X_DIMENSION/96))x$((Y_DIMENSION/96))cm) · $FOCAL_LENGTH; $F_NUMBER ${EXP_TIME}s ${ISO}ISO"
