#!/bin/sh

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$1" in
"C-c")  while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-e")  while read file; do gimp "$file" & done ;;
"C-E")  while read file; do rawtherapee "$file" & done ;;
"C-r")  rotate 270 ;;
"C-R")  rotate 180 ;;
esac
