#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &  # Launch sxhkd

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        3
bspc config window_gap          5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

# Rules
bspc rule -a matplotlib state=floating

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# Autostart
sh ~/.screenlayout/monitor.sh &                               # Set display from arandr saved script
~/.config/polybar/launch.sh &                                 # Bar
/usr/bin/dunst &                                              # Notifications
nitrogen --restore &                                          # Wallpaper
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &   # polkit
dex -a -s /etc/xdg/autostart/:~/.config/autostart/            # dex
picom -CGb &                                                  # picom
nm-applet --indicator &                                       # NetworkManager
xsetroot -cursor_name left_ptr &                              # Cursor
setxkbmap -option ctrl:nocaps
~/.config/bspwm/scripts/low_bat_notifier.sh                   # Low battery notifier
