#!/bin/bash

bspc config border_width 		2
bspc config split_ratio 		0.50
bspc config window_gap 			0
bspc config focus_follows_pointer 	false

bspc config normal_border_color	 "#1B1D25"
bspc config focused_border_color "#BD93F9"

if [[ $(xrandr --query | grep 'DisplayPort-0') = *\ connected* ]];
then
	bspc monitor "eDP" -d 5 6 7 8 9 
	bspc monitor "DisplayPort-0" -d 1 2 3 4
else
	bspc monitor "eDP" -d 1 2 3 4 5 6 7 8 9
fi

bspc rule -a \* state=tiled
bspc rule -a feh state=pseudo_tiles
bspc rule -a gimp state=floating
bspc rule -a zoom state=floating
bspc rule -a slack state=floating

# Launch programs I use with bspwm
$HOME/.config/polybar/launch.sh
