#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          1
bspc config window_gap            5
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false
bspc config focused_border_color  "#f1f1f1"
bspc config normal_border_color   "#1c1c1c"
bspc config active_border_color   "#1c1c1c"

# Rules
bspc rule -a matplotlib state=floating

# Autostart
sxhkd &
picom -CGb &
polybar cvv &
nm-applet --indicator &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
blueman-applet &
insync &
