#!/bin/env bash

pgrep -x sxhkd >/dev/null || sxhkd &

if [ "$(hostname)" = "dumile" ]; then
	bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
	bspc monitor DP-3 -d 10
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width 3
bspc config window_gap 3
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false
bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"

# Rules
bspc rule -a matplotlib state=floating
bspc rule -a Spotify desktop=^8
bspc rule -a discord desktop=^9
bspc rule -a whatsapp-nativefier-d40211 desktop=^10

# Autostart
xrandr --output DP-0 --primary --right-of DP-3 --output DP-3 --rotation left
xsetroot -cursor_name left_ptr
setxkbmap -option ctrl:nocaps

polybar cvv &
sxhkd &
nm-applet --indicator &
blueman-applet &
spotify &
insync start
