#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Activate vi mode
set -o vi

# Misc settings
export PROMPT_DIRTRIM='2'		# Trim directory to the last 2 folders
HISTSIZE= HISTSIZEFILE=			# Infinite history
shopt -s histappend				# Append to history instead of overwriting
shopt -s expand_aliases
shopt -s checkwinsize
complete -cf sudo

# Environmental variables
export SHELL=/bin/bash
export EDITOR=nvim
export PATH=$PATH:$HOME/documents/git/tools
export GITDIR=$HOME/documents/git/
export ZETTELDIR=$HOME/documents/zk

[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases
[[ -f ~/.polyglot.sh ]] && . ~/.polyglot.sh
[[ -f ~/.fzf.sh ]] && . ~/.fzf.sh

# Created by `pipx` on 2022-02-16 18:49:08
export PATH="$PATH:/home/carlos/.local/bin"
