#!/bin/bash

# exa
alias ls='exa --group-directories-first'
alias ll='exa -lh --group-directories-first'
alias l.='exa -ad .* --group-directories-first'
alias ll.='exa -lhad .* --group-directories-first'

# n/vim
alias v='nvim'
alias vi='nvim'
alias vim='nvim'

# git
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gr='git restore'
alias gb='git branch'
alias go='git checkout'
alias gl='git logline'

# misc
alias ..='cd ..'
alias :q='exit'
alias pluto='julia -e "using Pluto; Pluto.run()"'
alias grep='grep --colour=auto'
alias tmux='tmux -2'
