#!/bin/bash 

git_branch() {
	git branch 2> /dev/null | \
		sed -e '/^[^*]/d' -e 's/* \(.*\)/ - \1/'
}

git_status() {
	git status --porcelain 2> /dev/null | \
		cut -c-2 | \
		sort | \
		uniq | \
		tr '\n' ' ' | \
		sed -e 's/ //g' -e 's/\(.\)\1*/(\1/' -e 's/\(.$\)/\1)/'
}

PS1="\[\033[0;37m\]\h\[\033[m\]"
PS1+="\[\033[1;32m\] :: \[\033[m\]"
PS1+="\w"
PS1+="\[\033[1;35m\]\$(git_branch)\[\033[m\]"
PS1+="\[\033[1;32m\] \$(git_status)\[\033[m\]"
PS1+="\[\033[1;33m\] ⟶  \[\033[m\]"
export PS1
